from pydantic_settings import BaseSettings
from prompts import (
    PREPROCESSOR_SYSTEM_PROMPT,
    PREPROCESSOR_USER_PROMPT_NO_CONTEXT,
    PREPROCESSOR_USER_PROMPT_WITH_CONTEXT,
)

class PreprocessorConfig(BaseSettings):
    """Configuration for the preprocessor."""

    LLM_RETRIES: int = 3
    
    PREPROCESSOR_SYSTEM_PROMPT: str = PREPROCESSOR_SYSTEM_PROMPT
    PREPROCESSOR_USER_PROMPT_NO_CONTEXT: str = PREPROCESSOR_USER_PROMPT_NO_CONTEXT
    PREPROCESSOR_USER_PROMPT_WITH_CONTEXT: str = PREPROCESSOR_USER_PROMPT_WITH_CONTEXT

